name: Code Review

permissions:
  contents: read
  pull-requests: write

on:
  pull_request:
    types: [ opened, reopened, synchronize ]

jobs:
  review:
    if: ${{ contains(github.event.*.labels.*.name, 'review') }}
    runs-on: ubuntu-latest
    environment: development
    steps:
      - uses: anc95/ChatGPT-CodeReview@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          # optional
          LANGUAGE: Korean
          MODEL: gpt-4o  # https://platform.openai.com/docs/models
          PROMPT: "변경전 소스에 대한 한줄 요약을 '## AS-IS', 변경후 소스에 대한 한줄 요약을 '## TO-BE' 라는 제목으로 요약해줘. 개선할 부분이 있다면 '## 개선' 이라는 제목으로 제안해줘. 예상되는 에러가 있다면 '## 주의' 라는 제목으로 알려줘."
          max_tokens: 4096
          MAX_PATCH_LENGTH: 4096
